spring:
  application:
    name: stock-chat

# Ollama 설정
langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: gpt-oss:20b
      temperature: 0.7

# KIS API 설정 (환경변수로 주입)
kis:
  api:
    app-key: PSuCWaBXnmbCzs43cP74emH3hEfXuk5aBQ1X
    app-secret: NQTcHHXkhXF09IQwZgXT+U5XG6ki9DyhUy4aBnchDJw3OgMloiO7jzNJQ6dd7jTKsgE1rwrUKVzBm1MwXK0INeFsXlIXjWPACe1T7usem1CZtNtKZhbnZOX4gHdDWjygIItzne/seGNu/BdIbUa4D2sDLzthGdaDBecVN/E1Ei66AZA8ff4=
    base-url: https://openapi.koreainvestment.com:9443
