spring:
  application:
    name: antigravity_test_01
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

firebase:
  service-account-file: classpath:firebase_key.json
